name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Install dependencies (if using Maven or Gradle)
    - name: Set up Maven
      uses: actions/setup-maven@v3
      with:
        maven-version: '3.8.1'

    # Run unit tests
    - name: Run tests
      run: mvn test  # O usa `gradle test` si usas Gradle

    # Run Checkstyle for code quality checks
    - name: Run Checkstyle
      run: mvn checkstyle:check  # Ejecutar Checkstyle con Maven
