name: Tests and Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-quality:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Java (JDK 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Cache Maven packages
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4. Install dependencies
    - name: Install dependencies
      run: mvn install -DskipTests

    # 5. Run tests
    - name: Run tests
      run: mvn test

    
